steps:
  # Paso 1: Instalar dependencias
  - name: 'node:18'
    entrypoint: npm
    args: ['ci']
    dir: '.'

  # Paso 2: Desplegar a Cloud Functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --gen2
      - --runtime=nodejs18
      - --region=${_REGION}
      - --source=.
      - --entry-point=main
      - --trigger-http
      - --allow-unauthenticated
      - --memory=512MB
      - --timeout=540s
      - --set-env-vars=NODE_ENV=${_NODE_ENV},OPENAI_API_KEY=${_OPENAI_API_KEY},DATABASE_ID=${_DATABASE_ID},ACCESS_TOKEN_KEY=${_ACCESS_TOKEN_KEY},REFRESH_TOKEN_KEY=${_REFRESH_TOKEN_KEY},SCOPE_KEY=${_SCOPE_KEY},TOKEN_TYPE_KEY=${_TOKEN_TYPE_KEY},EXPIRY_DATE_KEY=${_EXPIRY_DATE_KEY},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_PROJECT_ID=${_GOOGLE_PROJECT_ID},GOOGLE_AUTH_URI=${_GOOGLE_AUTH_URI},GOOGLE_TOKEN_URI=${_GOOGLE_TOKEN_URI},GOOGLE_AUTH_PROVIDER_X509_CERT_URL=${_GOOGLE_AUTH_PROVIDER_X509_CERT_URL},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GOOGLE_REDIRECT_URI=${_GOOGLE_REDIRECT_URI},FIREBASE_TYPE=${_FIREBASE_TYPE},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_PRIVATE_KEY_ID=${_FIREBASE_PRIVATE_KEY_ID},FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY},FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL},FIREBASE_CLIENT_ID=${_FIREBASE_CLIENT_ID},FIREBASE_AUTH_URI=${_FIREBASE_AUTH_URI},FIREBASE_TOKEN_URI=${_FIREBASE_TOKEN_URI},FIREBASE_AUTH_PROVIDER_X509_CERT_URL=${_FIREBASE_AUTH_PROVIDER_X509_CERT_URL},FIREBASE_CLIENT_X509_CERT_URL=${_FIREBASE_CLIENT_X509_CERT_URL},FIREBASE_UNIVERSE_DOMAIN=${_FIREBASE_UNIVERSE_DOMAIN}
      - --project=${_PROJECT_ID}

options:
  logging: CLOUD_LOGGING_ONLY

# Variables de sustitución que se configuran en los triggers
# _PROJECT_ID: ID del proyecto de GCP
# _FUNCTION_NAME: Nombre de la Cloud Function
# _REGION: Región de GCP
# _NODE_ENV: Entorno (qa o production)
# Todas las variables de entorno se configuran en el trigger