steps:
  # Paso 1: Instalar dependencias
  - name: "node:20"
    entrypoint: npm
    args: ["ci"]
    dir: "."

  # Paso 2: Desplegar a Cloud Functions
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - ${_FUNCTION_NAME}
      - --gen2
      - --runtime=nodejs20
      - --region=${_REGION}
      - --source=.
      - --entry-point=main
      - --trigger-http
      - --allow-unauthenticated
      - --memory=512MB
      - --timeout=540s
      - --set-env-vars=NODE_ENV=${_NODE_ENV}
      - --project=${_PROJECT_ID}

options:
  logging: CLOUD_LOGGING_ONLY
# Variables de sustitución que se configuran en los triggers
# _PROJECT_ID: ID del proyecto de GCP
# _FUNCTION_NAME: Nombre de la Cloud Function
# _REGION: Región de GCP
# _NODE_ENV: Entorno (qa o production)
# _ENV_SUFFIX: Sufijo para los secrets (QA o PROD)
